site_name: Gleaner Documentation

repo_url: https://github.com/gleanerio/gleanerdocs.github.io
edit_uri: blob/docs/
#theme: 'material'
#theme: 'mkdocs'
theme:
  name: material
#  name: 'readthedocs'
  features:
    #    - content.code.copy
    - navigation.sections
markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
# literate_nav must load after multirepo for the features to be available.
  - multirepo:
      # (optional) tells multirepo to cleanup the temporary directory after site is built.
      cleanup: true
  -  mermaid2
  - literate-nav
  -  mkdocs-jupyter
  - callouts
  # get a NoneType error, even when trying to generate in Geocodes-Metadata
#  - schema_reader:
#      include:
#        - "./docs/GeoCODES-Metadata/schemas/"
nav:
  - Gleaner: index.md

  - Running:
    - Quick Start: quicsktart.md
    - CLI: cli.md
    - Docker CLI: dockercli.md
  - Configuration: config.md
  - Applications:
      - Gleaner -JSONLD from Page: '!import https://github.com/gleanerio/gleaner?branch=dev_docs'
      - Nabu - Upload JSONLD to Graphstores: '!import https://github.com/gleanerio/nabu?branch=dev_docs'
  - Communities and Fair: faircontext.md


